# Generated by Django 3.1 on 2020-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hasiruthota', '0002_auto_20200917_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
            ],
        ),
    ]
