# Generated by Django 3.1 on 2020-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hasiruthota', '0003_new_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price1', models.IntegerField()),
            ],
        ),
    ]
